name: Scheduled URL Check

on:
  schedule:
    # Run every 8 hours (at 00:00, 08:00, 16:00 UTC)
    - cron: '0 */8 * * *'
  workflow_dispatch: # Allow manual trigger

jobs:
  check-url:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        
    - name: Run URL check script
      run: python script.py
      
    - name: Upload logs
      uses: actions/upload-artifact@v3
      if: always()
      with:
        name: url-check-logs
        path: app.log
